version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: serpent-db.c1yqesg669dd.eu-central-1.rds.amazonaws.com
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
      MYSQL_DATABASE: serpent_surge_db

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
