
- name: Deploy Serpent Surge App with Backup Timer
  hosts: all
  become: yes

  vars:
    docker_compose_version: "1.29.2"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure docker-compose is executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
        state: file

    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Start the containers
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu

    - name: Copy backup script to EC2
      copy:
        src: 02-backup-score.sh
        dest: /home/ubuntu/02-backup-score.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy systemd service file
      copy:
        src: score-backup.service
        dest: /etc/systemd/system/score-backup.service
        mode: '0644'

    - name: Copy systemd timer file
      copy:
        src: score-backup.timer
        dest: /etc/systemd/system/score-backup.timer
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start backup timer
      systemd:
        name: score-backup.timer
        enabled: yes
        state: started
